:global:
  componentName: backup-k8up
  githubUrl: https://github.com/projectsyn/component-backup-k8up
  feature_goUnitTests: false
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - v1
      - v2

.gitignore:
  additionalEntries:
    - jsonnetfile.json

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
