:global:
  componentName: backup-k8up
  githubUrl: https://github.com/projectsyn/component-backup-k8up
  feature_goUnitTests: false
  feature_goldenTests: true

docs/antora.yml:
  name: backup-k8up
  title: backup-k8up

.gitignore:
  additionalEntries:
    - jsonnetfile.json
