= Parameters

The parent key for all of the following parameters is `backup_k8up`.


== `enabled`

[horizontal]
type:: bool
default:: `true`

Whether to create the ArgoCD app for the component.
Setting this to false, effectively disables the component from being deployed.

NOTE: The manifests will still appear in the catalog, but without the ArgoCD app they won't get deployed.

== `crd`

[horizontal]
type:: string
default:: `k8up-crd.yaml`

The name of the CRD yaml File.

Use `k8up-crd.yaml` (default) for K8s >= 1.16
Change to `k8up-crd-legacy.yaml` for K8s <= 1.15 (e.g. OpenShift 3.11)

See https://github.com/appuio/charts/tree/master/k8up#handling-crds

== `helmValues`

[horizontal]
type:: dict
default:: See `class/defaults.yaml`

Values passed to Helm. See https://github.com/appuio/charts/tree/master/k8up

== `namespace`

[horizontal]
type:: string
default:: `syn-backup`

The namespace in which to deploy this component.

== `global_backup_config.enabled`

[horizontal]
type:: bool
default:: `true`

Enable global K8up configuration (via environment variables)

== `global_backup_config.default_backup_bucket`

[horizontal]
type:: string
default: `${cluster:name}-k8up-backups`

== `global_backup_config.s3_credentials`

[horizontal]
type:: dict
default:: `{'accesskey': '', 'secretkey': '', 'secretname': 'global-bucket-credentials', 'accesskeyname': 'username', 'secretkeyname': 'password'}`


== `global_backup_config.backup_secret`

[horizontal]
type:: dict
default:: `{'name': 'global-backup-password', 'password': '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/password}'}`

== `global_backup_config.s3restore_credentials`

[horizontal]
type:: dict
default:: `{'accesskey': '', 'secretkey': '', 'secretname': 'global-restore-credentials', 'accesskeyname': 'username', 'secretkeyname': 'password'}`


== `global_backup_config.restore_s3endpoint`

[horizontal]
type:: string
default:: `null`

== `global_backup_config.restore_bucket`

[horizontal]
type:: string
default:: `null`

`global_backup_config.keepjobs`

[horizontal]
type:: string
default:: `3`

== `global_backup_config.stats_endpoint`

[horizontal]
type:: string
default:: `null`

== `global_backup_config.s3_endpoint`

[horizontal]
type:: string
default:: `null`

== `backofflimit`

[horizontal]
type:: string
default:: `2`

== `annotation`

[horizontal]
type:: string
default:: `k8up.syn.tools/backup`

== `backupcommandannotation`

[horizontal]
type:: string
default:: `k8up.syn.tools/backupcommand`

== `alert_rule_filters`

[horizontal]
type:: dict
default:: `{'namespace': 'namespace=~"syn.*"'}

== `prometheus_push_gateway`

[horizontal]
type:: string
default:: `'http://platform-prometheus-pushgateway.syn-synsights.svc:9091'`

== `prometheus_name`

[horizontal]
type:: string
default:: `'main'`

PrometheusRule objects get the label `prometheus`.
This label will be used by the Prometheus operator to select the rules to render for a prometheus instance.
This parameter allows to set the value of that label.

[NOTE]
====
If the component Synsights is being used, ensure that this value matches with `parameters.synsights.prometheus.name`.
It is suggested to do this within you global configuration hierarchy.
====

== `monitoring_enabled`

[horizontal]
type:: bool
default:: `true`


== `alert_thresholds`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
k8up_slow_backup_job_duration_seconds: 1200
----

Dict which holds configuration values for the alerts in `monitoring_alerts`.
This allows users to make alert expressions configurable without having to copy-paste the entire Prometheus query.

* `k8up_slow_backup_job_duration_seconds` configures the threshold in seconds above which alerts are generated for "slow" backup jobs.

== `monitoring_alerts`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
k8up_last_errors:
  annotations:
    message: Last backup for PVC {{ $labels.pvc }} in namespace {{ $labels.instance }} had {{ $value }} errors
  expr: baas_backup_restic_last_errors{${backup_k8up:alert_rule_filters:namespace}} > 0
  for: 1m
  labels:
    severity: critical
K8upBackupFailed:
  annotations:
    message: Job in {{ $labels.exported_namespace }} of type {{ $labels.jobType }} failed
  expr: rate(k8up_jobs_failed_counter[1d]) > 0
  for: 1m
  labels:
    severity: critical
K8upBackupNotRunning:
  annotations:
    message: No K8up jobs were run in {{ $labels.exported_namespace }} within the last 24 hours. Check the operator, there might be a deadlock
  expr: sum(rate(k8up_jobs_total[25h])) == 0 and on(namespace) k8up_schedules_gauge > 0
  for: 1m
  labels:
    severity: critical
K8upJobStuck:
  annotations:
    message: Queued K8up jobs in {{ $labels.exported_namespace }} for the last hour.
  expr: k8up_jobs_queued_gauge{jobType="backup"} > 0 and on(namespace) k8up_schedules_gauge > 0
  for: 1h
  labels:
    severity: critical
K8upSlowBackup:
  annotations:
    message: Backup job {{ $labels.job_name }} in {{ $labels.namespace }} took {{ $value|humanizeDuration }} to complete
  expr: (kube_job_status_completion_time{job_name=~"^backupjob-.*$"} - kube_job_status_start_time) > ${backup_k8up:alert_thresholds:k8up_slow_backup_job_duration_seconds}
  for: 1m
  labels:
    severity: warning
----

Alert definitions to deploy in a `PrometheusRule` object.
The dict is transformed to a list of alerting rules by the component.
Keys in the dict are used to add the field `alert: <key>` to each resulting alerting rule.
This structure is chosen to easily adjust individual alert configurations in the hierarchy.

== Example

[source,yaml]
----
namespace: example-namespace
global_keepjobs: "1"
global_s3_credentials:
  accesskey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/access-key}'
  secretkey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/secret-key}'
global_s3restore_credentials:
  accesskey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/restore-access-key}'
  secretkey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/restore-secret-key}'
global_restore_s3endpoint: https://s3endpoint.example.com
global_restore_bucket: example-restore-bucket
monitoring_alerts:
  K8upJobStuck:
    annotations:
      runbook_url: https://example.com/k8up_runbook.md
----
