= Parameters

The parent key for all of the following parameters is `backup_k8up`.


== `enabled`

[horizontal]
type:: bool
default:: `true`

Whether to create the ArgoCD app for the component.
Setting this to false, effectively disables the component from being deployed.

NOTE: The manifests will still appear in the catalog, but without the ArgoCD app they won't get deployed.

== `charts`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

The default K8up Helm chart version to use.

== `images`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

The default Docker image locations and tags to use for K8up (key `k8up`) and Wrestic (key `wrestic`).

Entries in this dict should be dictionaries with keys `registry`, `repository`, and `tag`.
This structure provides the basis for https://syn.tools/syn/SDDs/0017-maintenance-with-renovate.html[dependency maintenance with Renovate].

Please customize K8up and Wrestic image locations and tags in this dict
instead of directly in `helmValues`.

The value of `k8up.tag` in this dict is used by the component to select the CRD YAML to download.

== `crd`

[horizontal]
type:: string
default:: `k8up-crd.yaml`

The name of the CRD yaml File.

Use `k8up-crd.yaml` (default) for K8s >= 1.16
Change to `k8up-crd-legacy.yaml` for K8s <= 1.15 (for example OpenShift 3.11)

See https://github.com/appuio/charts/tree/master/k8up#handling-crds

== `helmValues`

[horizontal]
type:: dict
default:: See `class/defaults.yaml`

Values passed to Helm. See https://github.com/appuio/charts/tree/master/k8up

== `namespace`

[horizontal]
type:: string
default:: `syn-backup`

The namespace in which to deploy this component.

== `global_backup_config.enabled`

[horizontal]
type:: bool
default:: `true`

Enable global K8up configuration (via environment variables)

== `global_backup_config.default_backup_bucket`

[horizontal]
type:: string
default: `${cluster:name}-k8up-backups`

== `global_backup_config.s3_credentials`

[horizontal]
type:: dict
default:: `{'accesskey': '', 'secretkey': '', 'secretname': 'global-bucket-credentials', 'accesskeyname': 'username', 'secretkeyname': 'password'}`


== `global_backup_config.backup_secret`

[horizontal]
type:: dict
default:: `{'name': 'global-backup-password', 'password': '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/password}'}`

== `global_backup_config.s3restore_credentials`

[horizontal]
type:: dict
default:: `{'accesskey': '', 'secretkey': '', 'secretname': 'global-restore-credentials', 'accesskeyname': 'username', 'secretkeyname': 'password'}`


== `global_backup_config.restore_s3endpoint`

[horizontal]
type:: string
default:: `null`

== `global_backup_config.restore_bucket`

[horizontal]
type:: string
default:: `null`

== `global_backup_config.keepjobs`

[horizontal]
type:: string
default:: `3`

Sets the number of old jobs to keep when cleaning up, applies to all job types.

Deprecated: Use `global_backup_config.successful_jobs_history_limit` and `global_backup_config.failed_jobs_history_limit` instead.
Overridden by `global_backup_config.successful_jobs_history_limit` and `global_backup_config.failed_jobs_history_limit` respectively.

== `global_backup_config.successful_jobs_history_limit`

[horizontal]
type:: string
default:: `null`

Sets the number of old, successful jobs to keep when cleaning up, applies to all job types.
Overrides `global_backup_config.keepjobs`.
If neither `global_backup_config.keepjobs` nor this parameter are set, the https://k8up.io/k8up/1.2.0/references/config-reference.html[K8up default value] for the configuration is used.

== `global_backup_config.failed_jobs_history_limit`

[horizontal]
type:: string
default:: `null`

Sets the number of old, failed jobs to keep when cleaning up, applies to all job types.
Overrides `global_backup_config.keepjobs`.
If neither `global_backup_config.keepjobs` nor this parameter are set, the https://k8up.io/k8up/1.2.0/references/config-reference.html[K8up default value] for the configuration is used.

== `global_backup_config.stats_endpoint`

[horizontal]
type:: string
default:: `null`

== `global_backup_config.s3_endpoint`

[horizontal]
type:: string
default:: `null`

== `backofflimit`

[horizontal]
type:: string
default:: `2`

== `annotation`

[horizontal]
type:: string
default:: `k8up.syn.tools/backup`

== `backupcommandannotation`

[horizontal]
type:: string
default:: `k8up.syn.tools/backupcommand`

== `alert_rule_filters`

[horizontal]
type:: dict
default:: `{'namespace': 'namespace=~"syn.*"'}

== `prometheus_push_gateway`

[horizontal]
type:: string
default:: `'http://platform-prometheus-pushgateway.syn-synsights.svc:9091'`

== `prometheus_name`

[horizontal]
type:: string
default:: `'main'`

PrometheusRule objects get the label `prometheus`.
This label will be used by the Prometheus operator to select the rules to render for a prometheus instance.
This parameter allows to set the value of that label.

[NOTE]
====
If the component Synsights is being used, ensure that this value matches with `parameters.synsights.prometheus.name`.
It's suggested to do this within you global configuration hierarchy.
====

== `monitoring_enabled`

[horizontal]
type:: bool
default:: `true`


== `alert_thresholds`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
k8up_slow_backup_job_duration_seconds: 1200
----

Dict which holds configuration values for the alerts in `monitoring_alerts`.
This allows users to make alert expressions configurable without having to copy-paste the entire Prometheus query.

* `k8up_slow_backup_job_duration_seconds` configures the threshold in seconds above which alerts are generated for "slow" backup jobs.

== `job_failed_alerts_for`

[horizontal]
type:: dict
valid keys:: `['archive', 'backup', 'check', 'prune', 'restore']`
default:: [See `class/defaults.yml`|https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml]

Dict which controls the set of JobFailed alert rules to create.
Valid keys are `archive`, `backup`, `check`, `prune`, and `restore`.
The value for each key is expected to be a dict with keys `enabled` and `overrides`.
The value for key `enabled` should be a boolean.
This key controls whether the corresponding alert rule is created.
The value for key `overrides` is merged with the object configured in `job_failed_alert_template`.
When configuring overrides, Jsonnet merges arrays and objects from the template with their counterparts in `overrides`.
This key allows users to customize any alert properties for individual `JobFailed` alerts.
The fields are overridden before interpolating `%(type)s`.

== `job_failed_alert_template`

[horizontal]
type:: dict
default:: [See `class/defaults.yml`|https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml]

The template for the JobFailed alert rules.
%(type)s in `alert` and `expr` is replaced by the types defined in `job_failed_alerts_for`.

== `monitoring_alerts`

[horizontal]
type:: dict
default:: [See `class/defaults.yml`|https://github.com/projectsyn/component-backup-k8up/blob/master/class/defaults.yml]

Alert definitions to deploy in a `PrometheusRule` object.
The dict is transformed to a list of alerting rules by the component.
Keys in the dict are used to add the field `alert: <key>` to each resulting alerting rule.
This structure is chosen to easily adjust individual alert configurations in the hierarchy.

== Example

[source,yaml]
----
namespace: example-namespace
global_backup_config:
  successful_jobs_history_limit: 1
  failed_jobs_history_limit: 1
  s3_credentials:
    accesskey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/access-key}'
    secretkey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/secret-key}'
  s3restore_credentials:
    accesskey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/restore-access-key}'
    secretkey: '?{vaultkv:${cluster:tenant}/${cluster:name}/global-backup/restore-secret-key}'
  restore_s3endpoint: https://s3endpoint.example.com
  restore_bucket: example-restore-bucket
monitoring_alerts:
  K8upJobStuck:
    annotations:
      runbook_url: https://example.com/k8up_runbook.md
----
